name: Price Tracker Automation

on:
  schedule:
    # Runs at 12pm, 4pm, 8pm, and 12am Riyadh Time
    - cron: '0 9,13,17,21 * * *'
  workflow_dispatch:

jobs:
  scrape_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Scraper
        env:
          URL_PAGE: ${{ secrets.URL_PAGE }}
          CLASS_NAME: ${{ secrets.CLASS_NAME }}
          CLASS_ELEMENT_TYPE: ${{ secrets.CLASS_ELEMENT_TYPE }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py
